### Create a Course
POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker-compose"
}

### Get all Courses
GET http://localhost:3333/courses

### Get by id
GET http://localhost:3333/courses/2c21ff26-302c-4901-924e-157a75c7991e

### Update a Course
PUT http://localhost:3333/courses/2c21ff26-302c-4901-924e-157a75c7991e
Content-Type: application/json

{
  "description": "Um curso muito bom sobre fastify"
}

### Delete a Course
DELETE http://localhost:3333/courses/2c21ff26-302c-4901-924e-157a75c7991e
